site_name: ElectionGuard Voting Site (docs.egvote.us)
# site_description:
# site_author:
# google_analytics:
# remote_branch: for gh-deploy to GithubPages
# remote_name: for gh-deploy to Github Pages
# copyright:
docs_dir: "docs"
repo_url: https://github.com/microsoft/electionguard/
nav:
  - Home: index.md
  - FAQ: faq.md
plugins:
  - search
  - mermaid2:
      arguments:
        securityLevel: "loose"
        htmlLabels: true
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.ico
  logo: images/electionguard-logo.png
  font:
    text: Segoe UI
  palette:
    scheme: default
    accent: indigo
    link: indigo
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/analytics.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
